apiVersion: v1
kind: Namespace
metadata:
  name: flask-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: your_app_image:latest # ← your local image
        imagePullPolicy: IfNotPresent # ← don’t try to pull
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: postgresql://user:pass@host:5432/db # ← update with your DB connection string
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-app
spec:
  selector:
    app: flask
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007
