apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
  namespace: flask-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard # Adjust storage class as needed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest # Use the official Postgres image version you prefer
        por:
        - containerPort: 5432
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: POSTGRES_DB
          value: db # Update with your DB name
        - name: POSTGRES_USER
          value: user # Update with your DB user
        - name: POSTGRES_PASSWORD
          value: pass # Update with your DB password
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: pgdata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: flask-app
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
