---
- name: Install NGINX and serve “Hello Ansible”
  hosts: web
  become: true

  vars:
    html_dest: /var/www/html/index.html
    hello_msg: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="utf-8">
        <title>Hello Ansible</title>
        <style>
          body { font-family: sans-serif; text-align: center; margin-top: 15%; }
          h1   { font-size: 3rem; color: #0d6efd; }
        </style>
      </head>
      <body>
        <h1>Hello from Ansible </h1>
        <p>This page was deployed automatically.</p>
      </body>
      </html>

  tasks:
    - name: Update apt cache & install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Write Hello Ansible page
      copy:
        content: "{{ hello_msg }}"
        dest: "{{ html_dest }}"
        owner: root
        group: root
        mode: "0644"

    - name: Ensure NGINX is started and enabled
      systemd:
        name: nginx
        state: started
        enabled: true
